name: Deploy to GitHub Pages
on:
  push:
    branches: [master] # Trigger on push to the main branch
jobs:
  deploy:
    runs-on: ubuntu-latest # Run on Ubuntu runner
    steps:
      - uses: actions/checkout@v3 # Checkout code from repository
      - name: Use Node.js 16
        uses: actions/setup-node@v4
        with:
          node-version: 18 # You can adjust the Node.js version here
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
